name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  workflow_dispatch:
  schedule:
    - cron: "30 5 * * *"
    - cron: "30 13 * * *"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

      - name: Notify Slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: cypress-test-saka-prj
          SLACK_USERNAME: Cypress Test Result
          SLACK_TITLE: Cypress test results for Saka.fi
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE_ON_FAILURE: "@Adam Krolak, please check the test results :pepebeaten:"
          SLACK_ICON: https://saka.fi/_next/image?url=%2Fassets%2Flogo%2Fsaka-logo.webp&w=96&q=75

      - name: Notify Slack
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: cypress-test-saka-prj
          SLACK_USERNAME: Cypress Test Result
          SLACK_TITLE: Cypress test results for Saka.fi
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE_ON_SUCCESS: "Everything work as expected :rocket:  :pepe-clap:"
          SLACK_ICON: https://saka.fi/_next/image?url=%2Fassets%2Flogo%2Fsaka-logo.webp&w=96&q=75
